force-app/main/default/objects/Support_Case__c/Support_Case__c.object-meta.xml
<CustomObject>
    <label>Support Case</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Support Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Support_Case__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Medium</fullName>
                <default>true</default>
                <label>Medium</label>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Support_Case__c/fields/SLA_Hours__c.field-meta.xml
<CustomField>
    <fullName>SLA_Hours__c</fullName>
    <label>SLA Hours</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Support_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SupportCaseController.cls
public with sharing class SupportCaseController {

    @AuraEnabled
    public static Id createSupportCase (
        String subject,
        Decimal slaHours,
        String status){
            Support_Case__c sc = new Support_Case__c(
                Name = subject,
                SLA_Hours__c = slaHours,
                Status__c = status
            );

            insert sc; // This will trigger the CaseTriggerHandler and update the Priority__c field based on SLA_Hours__c
            return sc.Id;
        }

        @AuraEnabled
        public static List<Support_Case__c> getCases() {
            return [
                SELECT Name, SLA_Hours__c, Status__c, Priority__c
                FROM Support_Case__c
                ORDER BY CreatedDate DESC
                LIMIT 10
            ];
        }
    }
 